apiVersion: batch/v1
kind: Job
metadata:
  name: eventdb-migration
  labels:
    {{- include "eventapi_ingester.labels.all" . | nindent 4 }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: eventdb-migration
      labels:
        {{- include "eventapi_ingester.labels.all" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.customServiceAccount | default (include "eventapi_ingester.name" .) }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      initContainers:
        - name: db-wait
          image: alpine:3.10
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Postgres..."

              while ! nc -z {{ .Values.applicationConfig.postgres.connection.host }} {{ .Values.applicationConfig.postgres.connection.port }}; do
                sleep 1
              done

              echo "Postgres started!"
      containers:
        - name: eventapi_ingester
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ required "A value is required for .Values.image.tag" .Values.image.tag }}
          args:
            - --migrateDatabase
            - --config
            - /config/application_config.yaml
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 -}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: user-config
              mountPath: /config/application_config.yaml
              subPath: {{ include "eventapi_ingester.config.filename" . }}
              readOnly: true
            {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 -}}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: user-config
          secret:
            secretName: {{ include "eventapi_ingester.config.name" . }}
        {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
        {{- end }}
