application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 10s
  missingJobEventReconciliationInterval: 15s
  jobLeaseRenewalInterval: 15s
  jobLeaseCleanupInterval: 5s
  allocateSpareClusterCapacityInterval: 5s
armada:
  url : "localhost:50051"
events:
  url : "localhost:50051"
authentication:
  enableAuthentication: false
