application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 15s
  missingJobEventReconciliationInterval: 15s
  jobLeaseRenewalInterval: 30s
  jobLeaseCleanupInterval: 30s
  allocateSpareClusterCapacityInterval: 2s
armada:
  url : "localhost:50051"
events:
  url : "localhost:50051"
authentication:
  enableAuthentication: false
