scheduling:
  queueLeaseBatchSize: 1000
  maximalResourceFractionToSchedulePerQueue:
    memory: 0.99
    cpu: 0.99
  maximalResourceFractionPerQueue:
    memory: 0.99
    cpu: 0.99
  maximalClusterFractionToSchedule:
    memory: 0.99
    cpu: 0.99
  defaultJobLimits:
    cpu: 1
    memory: 1Gi
    ephemeral-storage: 8Gi
  defaultJobTolerations:
    - key: "example.com/default_toleration"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
eventapi:
  enabled : true
  queryConcurrency: 100
  updateTopic: "persistent://armada/armada/sequenceupdates"
  PollPeriod: 100ms
  QueryBatchDuration: 100ms
  postgres:
    maxOpenConns: 10
    maxIdleConns: 5
    connection:
      host: postgres
      port: 5432
      user: postgres
      password: psw
      dbname: postgres
      sslmode: disable