alertmanager:
  enabled: false

grafana:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
  service:
    type: NodePort
    nodePort: 30002

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
  tlsProxy:
    enabled: false
  createCustomResource: false
