kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: armada-test
nodes:
- role: control-plane
  image: kindest/node:v1.21.1  
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80 # port of the nginx ingress controller
    hostPort: 5001 # expose ingresses on localhost:5001
    protocol: TCP
  - containerPort: 3001 # arbitrary port used to test "node port services"
    hostPort: 3001 # expose service on localhost:3001
    protocol: TCP