apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "armada.labels.all" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "armada.labels.identity" . | indent 6 }}
  template:
    metadata:
      name: {{ include "armada.name" . }}
      labels:
{{ include "armada.labels.all" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "armada.name" . }}
      containers:
        - name: armada
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ required "A value is required for .Values.image.tag" .Values.image.tag }}
          args:
            - --config
            - /config/application_config.yaml
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: user-config
              mountPath: /config/application_config.yaml
              subPath: {{ include "armada.application.config.filename" . }}
      volumes:
        - name: user-config
          configMap:
            name: {{ include "armada.config.name" . }}
