apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "armada.labels.all" . | indent 4 }}
spec:
  rules:
  - host: {{ required "A value is required for .Values.hostname" .Values.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "armada.name" . }}
            servicePort: {{ .Values.applicationConfig.grpcPort }}
