apiVersion: v1
kind: Service
metadata:
  name: {{ include "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "armada.labels.all" . | indent 4 }}
spec:
  selector:
{{ include "armada.labels.identity" . | indent 4 }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.applicationConfig.grpcPort }}
